sudo: required
language: cpp
services: docker

install:
- bash ./get_source.sh -openj9-repo=https://github.com/JamesKingdon/openj9.git -openj9-branch=arm
  -omr-repo=https://github.com/JamesKingdon/openj9-omr.git -omr-branch=arm
- cd ..; wget https://github.com/AdoptOpenJDK/openjdk9-openj9-nightly/releases/download/jdk-9%2B181-20172711/OpenJDK9-OPENJ9_x64_Linux_20172711.tar.gz;
  tar xf OpenJDK9-OPENJ9_x64_Linux_20172711.tar.gz
- cd openj9-openjdk-jdk9/openj9/buildenv/docker/jdk9/armhf_CC/; docker build -t openj9arm .

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/openj9-openjdk-jdk9 -v ${TRAVIS_BUILD_DIR%/openj9-openjdk-jdk9}/jdk-9+181:/root/buildjdk
  -t openj9arm /bin/sh -c "cd openj9-openjdk-jdk9 && ./build-docker-arm"

before_deploy:
- git config --local user.name "James Kingdon"
- git config --local user.email "jkingdon@ca.ibm.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: XHpEHIn9De7etq6lt6uU97r0F8AXqwUjxW5poJxlX0YN6Ucpb1mC7Gh23zpQDdnT61k0fTwVaGzgKRoyEWcO4nnXT7CvZ+sKu8B34C6ARKaTkzt/N1CJ6dNEUbYmgp655l3Djn7r/3xk+8VdfEd4cBtNObfX+RtSejcBJWHk/RTZ1QHC16J7Z2YkRFLiKL2nxKhIMzyKwhUDOrnwSDWMEqPww6TCN4rgfTvSfR3JO+bvrUaYlEvFTfOE0xIB8lfhYtYP7ktr3YVzC9DIR4ja/rH3DjlmxCP+TdAxrFDivQSDqChZdWTUhjSvBbOEtU6Hw0bJRw8wxi7HQTyYn8Ik+Eneh0MF4DF0uTOdeiCzCTq8EbiPs/CTieQI5pHxzUmP2alD5WtK9LSl8tieBv00oHfSmBrk23VmWCdzjGuU0CehHZVZFBwwhEXZD7hZFXvVJ3DaSwdANWsTiL/0mS9b+T10RnAt4EqGkVd/d1eRyuU55b5HW2bxPGlFdxTfR1C5RST92c3sRL4Vk/KIIj2nRWcB50XQRNB5wyC+uZPc5VTXJ9lVdxJJV+/qFdvMgsxv9ho86G2UupK/h4lhNaTpuxnYJnmV3i9U0RYtc+4I82tD6CkB1zYNwYZwZXCLjozh2lBzAskzdAqG+bzKMYzif+LlRUFNPGI4y9wwlplDn5w=
  file: 
   - ${TRAVIS_BUILD_DIR}/build/linux-arm-normal-server-release/images/jdk.zip
   - ${TRAVIS_BUILD_DIR}/build/linux-arm-normal-server-release/images/jre.zip
  on:
    repo: JamesKingdon/openj9-openjdk-jdk9
    branch: arm
  prerelease: true
  name: Testing, pre-alpha build for armhf
  body: This is a prototype build with known problems, intended for testing and further development. To work around the currently known problems, invoke the JVM with -Xjit:disableDirectToJNI -Xgcpolicy:optthruput
